# Generated by Django 2.1.7 on 2019-07-13 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20190712_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='carrinho',
        ),
        migrations.AddField(
            model_name='compra',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livros.Livro'),
            preserve_default=False,
        ),
    ]
