# Generated by Django 2.1.7 on 2019-07-13 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_auto_20190712_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='livros.Livro'),
        ),
    ]
